# Generated by Django 5.2.7 on 2025-11-19 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameXO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=100, unique=True)),
                ('board', models.CharField(default='_________', max_length=9)),
                ('active_player', models.CharField(default='X', max_length=1)),
                ('state', models.CharField(choices=[('active', 'Active'), ('won', 'Won'), ('tie', 'Tie')], default='active', max_length=10)),
                ('winner', models.CharField(blank=True, max_length=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player_o', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_as_o', to=settings.AUTH_USER_MODEL)),
                ('player_x', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_x', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
